### PR TITLE
Remove also tooltips when removing layer

### PR DESCRIPTION
**Pull request by stefanlinner**
I've looked into issue #55 and I think I've managed to solve the problem of tooltips not being removed when a layer is removed. This also solves the issue of the map getting sluggish after calling `clear_layer()` and `add_layer()` many times. You can see the difference in this example: 

```r
library(mapgl)
library(sf)
library(shiny)
library(dplyr)

nc <- st_read(system.file("shape/nc.shp", package="sf")) %>%
  mutate(label = paste0(NAME, "<br>", AREA, "<br>", PERIMETER))


ui <-
  fluidPage(
    actionButton("click", "Click"),
    mapboxglOutput("map")
  )

server <- function(input, output, session) {

  output$map <- renderMapboxgl({
    mapboxgl() %>%
      fit_bounds(
        nc,
        animate = FALSE
      ) |>
      add_fill_layer(
        "fill",
        source = nc,
        fill_color = interpolate(
          column = "AREA",
          values = c(min(nc[["AREA"]]), max(nc[["AREA"]])),
          stops = c("#f7fbff", "#08306b"),
          na_color = "lightgrey"
        ),
        tooltip = "label"
      )
  })

  myMapProxy <- mapboxgl_proxy("map", session)

  observeEvent(input$click, {

    for(i in 1:200){
      myMapProxy |>
        clear_layer("fill") |>
        add_fill_layer(
          "fill",
          source = nc,
          fill_color = interpolate(
            column = "AREA",
            values = c(min(nc[["AREA"]]), max(nc[["AREA"]])),
            stops = c("#f7fbff", "#08306b"),
            na_color = "lightgrey"
          ),
          tooltip = "AREA"
        )
    }

  })
}

shinyApp(
  ui = ui,
  server = server
)

```

### CODE REVIEW

**Comment by stefanlinner** [comment]
I added two functions to my solution: 

1. `set_tooltip()` which now allows to update tooltip variables and thus should close #42.
2. `set_source()` which uses mapGL's setData() function and allows to update the underlying source dataset of the layer.

**Comment by walkerke** [comment]
Thanks so much @stefanlinner!  I'll review as soon as I can.

**Comment by walkerke** [comment]
This looks great, thank you!  Merging and I'll get to work implementing on the MapLibre side as well.

**Comment by kmcd39** [comment]
I'm not sure they're expected to at this point, but these don't work currently on the MapLibre side.

**Comment by walkerke** [comment]
@kmcd39 that's right, Stefan's PR only covered Mapbox.  I think the code should be fairly similar but I haven't had the chance to go through translating it over yet.

**Comment by stefanlinner** [comment]
I'll try to find some more time the next days and open another PR for this :)

**Pull request merged**
